DROP DATABASE IF EXISTS chat;

CREATE DATABASE chat;

USE chat;

CREATE TABLE messages(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username TEXT(40) NOT NULL,
    text TEXT(1000) NOT NULL,
    upvotes INTEGER DEFAULT 0,
    img TEXT(400) NOT NULL,
    time_posted TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
